name: Recycler
main: de.craftlancer.recycler.Recycler
version: ${project.version}
description: Recycle your useless stuff!
commands:
    recycler:
        description: reloads config
permissions:
    recycler.admin:
        default: op
    recycler.item.<itemName>:
        default: false
        description: Allows you to recycle Items with the name <itemName>